#!/bin/sh
[ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh"


# history
HISTFILE=~/.config/zsh/.zsh_history

# source
plug "$HOME/.config/zsh/addon/aliases.zsh"
plug "$HOME/.config/zsh/addon/exports.zsh"
plug "$HOME/.config/zsh/addon/keybinds.zsh"

# plugins
plug "esc/conda-zsh-completion"
plug "zsh-users/zsh-autosuggestions"
# plug "hlissner/zsh-autopair"
plug "zap-zsh/supercharge"
#plug "zap-zsh/vim"
# plug "spaceship-prompt/spaceship-prompt"
# plug "zap-zsh/atmachine-prompt"
#plug "zap-zsh/zap-prompt"
plug "zap-zsh/fzf"
plug "zap-zsh/exa"
plug "zsh-users/zsh-syntax-highlighting"
#
plug "djui/alias-tips"
plug "arzzen/calc.plugin.zsh"
# eval "$(starship init zsh)"

plug "spaceship-prompt/spaceship-prompt"

# keybinds
bindkey '^ ' autosuggest-accept

export PATH="$HOME/.local/bin":$PATH

if command -v bat &> /dev/null; then
  alias cat="bat -pp"
  alias catt="bat"
fi
